import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // cubing.js is served from public/ and loaded at runtime, never bundled.
    // A value import would pull it back into the bundle, along with the worker
    // bugs that came with it. Type imports emit nothing and stay allowed.
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              regex: "^cubing(/.*)?$",
              allowTypeImports: true,
              message:
                "Load cubing through @/lib/cubing/runtime; it is not bundled. See docs/roadmap.md.",
            },
          ],
        },
      ],
      "no-restricted-syntax": [
        "error",
        {
          selector: "ImportExpression[source.value=/^cubing(\\u002F|$)/]",
          message:
            "Load cubing through @/lib/cubing/runtime; it is not bundled. See docs/roadmap.md.",
        },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by scripts/build-cubing.mjs.
    "public/cubing/**",
  ]),
]);

export default eslintConfig;
