/**
 * Seed script for the Learn section.
 *
 * Run with: npx tsx src/scripts/generate-seed-migration.ts
 *
 * Reads the TypeScript data files and generates a SQL migration file
 * at supabase/migrations/20260730000000_seed_learn_content.sql
 */

import { writeFileSync } from "fs";
import { join } from "path";

// Import data
import { OLL_CASES } from "./data/oll-data";
import { PLL_CASES } from "./data/pll-data";
import { ORTEGA_CASES } from "./data/ortega-data";
import { BEGINNER_LBL_SERIES, CFOP_INTRO_SERIES } from "./data/tutorial-data";

function escapeSQL(str: string): string {
  return str.replace(/'/g, "''");
}

function generateSQL(): string {
  const lines: string[] = [];

  lines.push("-- =============================================================");
  lines.push("-- Learn section seed data");
  lines.push("-- Generated by: npx tsx src/scripts/generate-seed-migration.ts");
  lines.push(`-- Generated at: ${new Date().toISOString()}`);
  lines.push("-- =============================================================");
  lines.push("");
  lines.push("BEGIN;");
  lines.push("");

  // -------------------------------------------------------
  // Tutorial Series & Steps
  // -------------------------------------------------------
  for (const series of [BEGINNER_LBL_SERIES, CFOP_INTRO_SERIES]) {
    lines.push(`-- Tutorial Series: ${series.title}`);
    lines.push(`INSERT INTO public.tutorial_series (slug, title, description, puzzle_type, difficulty, order_index, is_published)`);
    lines.push(`VALUES ('${escapeSQL(series.slug)}', '${escapeSQL(series.title)}', '${escapeSQL(series.description)}', '${series.puzzle_type}', '${series.difficulty}', ${series.order_index}, true)`);
    lines.push(`ON CONFLICT (slug) DO NOTHING;`);
    lines.push("");

    for (const step of series.steps) {
      lines.push(`INSERT INTO public.tutorial_steps (series_id, title, content_md, cube_state, order_index, is_published)`);
      lines.push(`VALUES (`);
      lines.push(`  (SELECT id FROM public.tutorial_series WHERE slug = '${escapeSQL(series.slug)}'),`);
      lines.push(`  '${escapeSQL(step.title)}',`);
      lines.push(`  '${escapeSQL(step.content_md)}',`);
      lines.push(`  '${escapeSQL(step.cube_state)}',`);
      lines.push(`  ${step.order_index},`);
      lines.push(`  true`);
      lines.push(`)`);
      lines.push(`ON CONFLICT (series_id, order_index) DO NOTHING;`);
      lines.push("");
    }
  }

  // -------------------------------------------------------
  // Algorithm Cases & Algorithms
  // -------------------------------------------------------
  const subsets = [
    { puzzle_type: "333", subset: "oll", cases: OLL_CASES },
    { puzzle_type: "333", subset: "pll", cases: PLL_CASES },
    { puzzle_type: "222", subset: "ortega", cases: ORTEGA_CASES },
  ];

  for (const { puzzle_type, subset, cases } of subsets) {
    lines.push(`-- =============================================================`);
    lines.push(`-- ${puzzle_type} ${subset.toUpperCase()} (${cases.length} cases)`);
    lines.push(`-- =============================================================`);
    lines.push("");

    for (const c of cases) {
      lines.push(`-- ${c.name}`);
      lines.push(`INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)`);
      lines.push(`VALUES ('${puzzle_type}', '${subset}', ${c.case_number}, '${escapeSQL(c.name)}', '${escapeSQL(c.description)}', '${escapeSQL(c.cube_state)}')`);
      lines.push(`ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET`);
      lines.push(`  name = EXCLUDED.name,`);
      lines.push(`  description = EXCLUDED.description,`);
      lines.push(`  cube_state = EXCLUDED.cube_state;`);
      lines.push("");

      for (const alg of c.algorithms) {
        lines.push(`INSERT INTO public.algorithms (case_id, moves, is_main, is_approved${alg.label ? ", label" : ""})`);
        lines.push(`VALUES (`);
        lines.push(`  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '${puzzle_type}' AND subset = '${subset}' AND case_number = ${c.case_number}),`);
        lines.push(`  '${escapeSQL(alg.moves)}',`);
        lines.push(`  ${alg.is_main},`);
        lines.push(`  true${alg.label ? `, '${escapeSQL(alg.label)}'` : ""}`);
        lines.push(`)`);
        lines.push(`ON CONFLICT DO NOTHING;`);
        lines.push("");
      }
    }
  }

  lines.push("COMMIT;");
  lines.push("");

  return lines.join("\n");
}

// Generate and write
const sql = generateSQL();
const outPath = join(__dirname, "../../supabase/migrations/20260730000000_seed_learn_content.sql");
writeFileSync(outPath, sql, "utf-8");
console.log(`✅ Migration written to: ${outPath}`);
console.log(`   Total size: ${(sql.length / 1024).toFixed(1)} KB`);
