import { test, expect, type Page } from "@playwright/test";

/**
 * cubing.js is served from public/cubing/ and imported at runtime (see
 * src/lib/cubing/runtime.ts). Headless checks cannot prove that works. The
 * failed route3 attempt passed every one of them and still broke in the
 * browser, because only a browser evaluates the module graph. So these tests
 * load real pages and wait for real output from cubing:
 *
 * - a rendered <twisty-player> (the cube preview), and
 * - a generated scramble, which comes out of cubing's search worker. Both
 *   bundlers used to break that worker.
 *
 * Run these against a production build (`npm run build`, then `next start`),
 * not only `npm run dev`. See docs/roadmap.md.
 */

/** Collects failures a hung dynamic import or broken worker would leave behind. */
function watchForLoadFailures(page: Page) {
  const problems: string[] = [];
  page.on("pageerror", (error) => problems.push(`pageerror: ${error.message}`));
  page.on("console", (msg) => {
    const text = msg.text();
    if (/worker instantiation|dynamically imported module|Failed to load module script/i.test(text)) {
      problems.push(`console: ${text}`);
    }
  });
  page.on("response", (res) => {
    const path = new URL(res.url()).pathname;
    if (res.status() >= 400 && (path.startsWith("/cubing/") || path.startsWith("/_next/static/"))) {
      problems.push(`HTTP ${res.status()} ${path}`);
    }
  });
  return problems;
}

/**
 * Resolves once a <twisty-player> has mounted with a real size and its loading
 * placeholder is gone. cubing renders into a *closed* shadow root, so the
 * canvas is not reachable by selector. For the 3D view, see expect3DCanvas.
 */
async function expectTwistyMounted(page: Page) {
  const player = page.locator("twisty-player").first();
  await expect(player).toBeAttached({ timeout: 30_000 });
  await player.scrollIntoViewIfNeeded();
  const box = await player.boundingBox();
  expect(box?.width).toBeGreaterThan(0);
  expect(box?.height).toBeGreaterThan(0);
  await expect(page.getByRole("status", { name: /loading cube/i })).toHaveCount(0);
}

/** Resolves once some <twisty-player> has drawn a sized 3D (WebGL) canvas. */
async function expect3DCanvas(page: Page) {
  await page.waitForFunction(
    async () => {
      type Player = HTMLElement & { experimentalCurrentCanvases(): Promise<HTMLCanvasElement[]> };
      for (const player of document.querySelectorAll<Player>("twisty-player")) {
        const canvases = await player.experimentalCurrentCanvases();
        if (canvases.some((c) => c.width > 0 && c.height > 0)) return true;
      }
      return false;
    },
    undefined,
    { timeout: 30_000, polling: 500 },
  );
}

test.describe("cubing.js runtime loading", () => {
  test("landing page: hero renders and the showcase cube preview draws", async ({ page }) => {
    const problems = watchForLoadFailures(page);
    await page.goto("/");

    await expect(page.getByRole("heading", { level: 1 })).toBeVisible();
    await expectTwistyMounted(page);
    // The showcase is the 3D view, which is the part that pulls in three.js.
    await expect3DCanvas(page);

    expect(problems).toEqual([]);
  });

  test("timer: a scramble is generated by cubing's worker and previewed", async ({ page }) => {
    const problems = watchForLoadFailures(page);
    await page.goto("/timer");

    const scramble = page.locator('[aria-label^="Scramble: "]').first();
    await expect(scramble).toBeVisible({ timeout: 30_000 });
    const label = (await scramble.getAttribute("aria-label")) ?? "";
    // A WCA 3x3 random-state scramble is roughly 17 to 22 face turns.
    expect(label.replace("Scramble: ", "").trim().split(/\s+/).length).toBeGreaterThan(10);

    await expectTwistyMounted(page);

    expect(problems).toEqual([]);
  });
});
