-- =============================================================
-- Learn section seed data
-- Generated by: npx tsx src/scripts/generate-seed-migration.ts
-- Generated at: 2026-07-29T18:17:20.993Z
-- =============================================================

BEGIN;

-- Tutorial Series: Beginner Method (Layer-By-Layer)
INSERT INTO public.tutorial_series (slug, title, description, puzzle_type, difficulty, order_index, is_published)
VALUES ('beginner', 'Beginner Method (Layer-By-Layer)', 'The easiest way to solve a 3x3 Rubik''s Cube. Learn to solve it layer by layer — first the white cross, then corners, the middle layer, and finally the last layer.', '333', 'beginner', 0, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.tutorial_steps (series_id, title, content_md, cube_state, order_index, is_published)
VALUES (
  (SELECT id FROM public.tutorial_series WHERE slug = 'beginner'),
  'The White Cross',
  '## Step 1: The White Cross

The first step is to form a white cross on the bottom of the cube (hold white on bottom).

### What you''re aiming for
- A white cross on the bottom face
- The edge colours match the centre colours on each side

### Tips
- There is no single algorithm for this — it''s intuitive
- Look for white edge pieces and move them to the bottom
- Make sure the side colours of each edge match the centre colours

This step takes practice. Don''t worry if it feels slow at first — everyone starts here.',
  '',
  0,
  true
)
ON CONFLICT (series_id, order_index) DO NOTHING;

INSERT INTO public.tutorial_steps (series_id, title, content_md, cube_state, order_index, is_published)
VALUES (
  (SELECT id FROM public.tutorial_series WHERE slug = 'beginner'),
  'First Layer Corners',
  '## Step 2: First Layer Corners

Now complete the first layer by inserting the white corner pieces.

### Key Algorithm
**R U R'' U''** — Repeat this up to 5 times to insert a corner.

### How to use it
1. Hold the cube with the white cross on the bottom
2. Find a white corner piece in the top layer
3. Position it above where it needs to go
4. Apply **R U R'' U''** until the corner drops into place

If a corner is already in the bottom layer but in the wrong position, use the same algorithm to pop it out first, then re-insert it correctly.',
  'R U R'' U''',
  1,
  true
)
ON CONFLICT (series_id, order_index) DO NOTHING;

INSERT INTO public.tutorial_steps (series_id, title, content_md, cube_state, order_index, is_published)
VALUES (
  (SELECT id FROM public.tutorial_series WHERE slug = 'beginner'),
  'Second Layer Edges',
  '## Step 3: Second Layer Edges

Insert the middle layer edge pieces to complete the first two layers (F2L).

### Right Insert
**U R U'' R'' U'' F'' U F**
Use this when the edge needs to go to the right.

### Left Insert
**U'' L'' U L U F U'' F''**
Use this when the edge needs to go to the left.

### How to use it
1. Hold the solved first layer on the bottom
2. Find an edge piece in the top layer that doesn''t have yellow
3. Align it with its matching centre
4. Determine if it goes right or left, then apply the correct algorithm',
  'U R U'' R'' U'' F'' U F',
  2,
  true
)
ON CONFLICT (series_id, order_index) DO NOTHING;

INSERT INTO public.tutorial_steps (series_id, title, content_md, cube_state, order_index, is_published)
VALUES (
  (SELECT id FROM public.tutorial_series WHERE slug = 'beginner'),
  'Yellow Cross',
  '## Step 4: Yellow Cross (OLL Step 1)

Form a yellow cross on the top face. You may see a dot, an L shape, or a line.

### The Algorithm
**F R U R'' U'' F''**

### When to use it
- **Dot** → Apply once to get an L, then continue
- **L shape** → Hold the L in the top-left corner, then apply
- **Line** → Hold it horizontal, then apply
- **Cross** → Already done! Move to the next step.',
  'F R U R'' U'' F''',
  3,
  true
)
ON CONFLICT (series_id, order_index) DO NOTHING;

INSERT INTO public.tutorial_steps (series_id, title, content_md, cube_state, order_index, is_published)
VALUES (
  (SELECT id FROM public.tutorial_series WHERE slug = 'beginner'),
  'Yellow Edges',
  '## Step 5: Orient Yellow Corners (OLL Step 2)

Get all yellow stickers facing up on the top layer.

### The Algorithm (Sune)
**R U R'' U R U2 R''**

### How to use it
1. Hold the cube with yellow on top
2. Find a corner where yellow is NOT on top
3. Hold it in the front-right position
4. Repeat **R U R'' U R U2 R''** until all yellow stickers face up
5. Don''t worry if the sides look scrambled — that''s normal',
  'R U R'' U R U2 R''',
  4,
  true
)
ON CONFLICT (series_id, order_index) DO NOTHING;

INSERT INTO public.tutorial_steps (series_id, title, content_md, cube_state, order_index, is_published)
VALUES (
  (SELECT id FROM public.tutorial_series WHERE slug = 'beginner'),
  'Position Yellow Corners',
  '## Step 6: Position the Corners (PLL Step 1)

Move the yellow corners to their correct positions (matching side colours).

### The Algorithm
**U R U'' L'' U R'' U'' L**

### How to use it
1. Look at the corners — find two that are already in the correct position (the colours match the sides, even if rotated)
2. If two correct corners are on the same side, hold that side as the back
3. If no corners are correct, apply the algorithm once from any angle
4. Repeat until all corners are in the right spots',
  'U R U'' L'' U R'' U'' L',
  5,
  true
)
ON CONFLICT (series_id, order_index) DO NOTHING;

INSERT INTO public.tutorial_steps (series_id, title, content_md, cube_state, order_index, is_published)
VALUES (
  (SELECT id FROM public.tutorial_series WHERE slug = 'beginner'),
  'Position Yellow Edges',
  '## Step 7: Position the Edges (PLL Step 2) — SOLVED!

The final step. Cycle the last-layer edges into their correct positions.

### Clockwise Cycle (Ua Perm)
**R U'' R U R U R U'' R'' U'' R2**

### Counter-clockwise Cycle (Ub Perm)
**R2 U R U R'' U'' R'' U'' R'' U R''**

### How to use it
1. Check if any edge is already in the correct position (colours match the centre)
2. Hold that solved edge as the back face
3. Determine if the other edges need to cycle clockwise or counter-clockwise
4. Apply the correct algorithm

🎉 **Congratulations!** If everything went right, your cube is now solved!',
  'R U'' R U R U R U'' R'' U'' R2',
  6,
  true
)
ON CONFLICT (series_id, order_index) DO NOTHING;

-- Tutorial Series: CFOP Introduction
INSERT INTO public.tutorial_series (slug, title, description, puzzle_type, difficulty, order_index, is_published)
VALUES ('cfop', 'CFOP Introduction', 'An overview of the CFOP speedcubing method — Cross, F2L, OLL, PLL. This is the most popular advanced method used by world-class speedcubers.', '333', 'intermediate', 1, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.tutorial_steps (series_id, title, content_md, cube_state, order_index, is_published)
VALUES (
  (SELECT id FROM public.tutorial_series WHERE slug = 'cfop'),
  'What is CFOP?',
  '## What is CFOP?

CFOP (also called the Fridrich Method) is the most widely used speedcubing method. It stands for:

- **C**ross — Solve the cross on the bottom
- **F2L** — First Two Layers (pair corners and edges intuitively)
- **O**LL — Orient Last Layer (make the top face all one colour)
- **P**LL — Permute Last Layer (move the top pieces to their correct positions)

### Why learn CFOP?
The beginner method solves in ~7 steps. CFOP reduces this to 4 stages with far fewer moves overall, making sub-30-second solves achievable.

### Prerequisites
You should be comfortable with the beginner method before learning CFOP. The cross step is similar, and understanding how pieces move will help with F2L.

### How to approach it
1. Start with cross on bottom (you may already do this)
2. Learn intuitive F2L (the biggest speed gain)
3. Learn 2-look OLL (7 algorithms instead of 57)
4. Learn 2-look PLL (6 algorithms instead of 21)
5. Gradually learn full OLL and PLL as you get faster',
  '',
  0,
  true
)
ON CONFLICT (series_id, order_index) DO NOTHING;

-- =============================================================
-- 333 OLL (57 cases)
-- =============================================================

-- OLL 1
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 1, 'OLL 1', 'Dot, Run', 'F R'' F'' R U2 F R'' F'' R2 U2 R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 1),
  'R U2 R2 F R F'' U2 R'' F R F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 2
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 2, 'OLL 2', 'Dot, Zamboni', 'f U R U'' R'' f'' F U R U'' R'' F''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 2),
  'F R U R'' U'' F'' f R U R'' U'' f''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 3
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 3, 'OLL 3', 'Dot, Anti-Frying Pan', 'F U R U'' R'' F'' U f U R U'' R'' f''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 3),
  'f R U R'' U'' f'' U'' F R U R'' U'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 4
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 4, 'OLL 4', 'Dot, Frying Pan', 'F U R U'' R'' F'' U'' f U R U'' R'' f''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 4),
  'f R U R'' U'' f'' U F R U R'' U'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 5
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 5, 'OLL 5', 'Square shape', 'r'' U'' R U'' R'' U2 r')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 5),
  'r'' U2 R U R'' U r',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 6
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 6, 'OLL 6', 'Square shape', 'r U R'' U R U2 r''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 6),
  'r U2 R'' U'' R U'' r''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 7
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 7, 'OLL 7', 'Lightning, Wide', 'r U2 R'' U'' R U'' r''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 7),
  'r U R'' U R U2 r''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 8
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 8, 'OLL 8', 'Lightning, Wide', 'r'' U2 R U R'' U r')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 8),
  'r'' U'' R U'' R'' U2 r',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 9
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 9, 'OLL 9', 'Kite', 'F U R U'' R2 F'' R U R'' U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 9),
  'R U R'' U'' R'' F R2 U R'' U'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 10
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 10, 'OLL 10', 'Kite', 'R U2 R'' F R'' F'' R U'' R U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 10),
  'R U R'' U R'' F R F'' R U2 R''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 11
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 11, 'OLL 11', 'Lightning', 'r U2 R'' F R'' F'' R U'' R U'' r''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 11),
  'r U R'' U R'' F R F'' R U2 r''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 12
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 12, 'OLL 12', 'Lightning', 'r R'' U R'' U2 R U R'' U R M')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 12),
  'M'' R'' U'' R U'' R'' U2 R U'' R r''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 13
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 13, 'OLL 13', 'Knight', 'F R U'' R'' U R U2 R'' U'' F''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 13),
  'F U R U2 R'' U'' R U R'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 14
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 14, 'OLL 14', 'Knight', 'F U F'' R'' F R U'' R'' F'' R')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 14),
  'R'' F R U R'' F'' R F U'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 15
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 15, 'OLL 15', 'Knight', 'l'' U'' l U'' L'' U L l'' U l')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 15),
  'l'' U'' l L'' U'' L U l'' U l',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 16
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 16, 'OLL 16', 'Knight', 'r U r'' U R U'' R'' r U'' r''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 16),
  'r U r'' R U R'' U'' r U'' r''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 17
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 17, 'OLL 17', 'Dot, Diagonal', 'M U R U R'' U'' r R2 F R F''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 17),
  'F R'' F'' R2 r'' U R U'' R'' U'' M''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 18
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 18, 'OLL 18', 'Dot', 'r'' U2 R U R'' U r2 U2 R'' U'' R U'' r''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 18),
  'r U R'' U R U2 r2 U'' R U'' R'' U2 r',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 19
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 19, 'OLL 19', 'Dot, Diagonal', 'F R'' F'' R M U R U'' R'' U'' R'' r')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 19),
  'r'' R U R U R'' U'' M'' R'' F R F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 20
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 20, 'OLL 20', 'Dot', 'M U R U R'' U'' M2 U R U'' r''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 20),
  'r U R'' U'' M2 U R U'' R'' U'' M''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 21
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 21, 'OLL 21', 'Cross, Pi', 'R U R'' U R U'' R'' U R U2 R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 21),
  'R U2 R'' U'' R U R'' U'' R U'' R''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 22
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 22, 'OLL 22', 'Cross, Wheel', 'R'' U2 R2 U R2 U R2 U2 R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 22),
  'R U2 R2 U'' R2 U'' R2 U2 R',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 23
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 23, 'OLL 23', 'Cross, Headlights', 'R'' U2 R'' D'' R U2 R'' D R2')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 23),
  'R2 D'' R U2 R'' D R U2 R',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 24
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 24, 'OLL 24', 'Cross, Chameleon', 'F R'' F'' r U R U'' r''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 24),
  'r U R'' U'' r'' F R F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 25
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 25, 'OLL 25', 'Cross, Bowtie', 'R'' F'' r U R U'' r'' F')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 25),
  'F'' r U R'' U'' r'' F R',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 26
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 26, 'OLL 26', 'Cross, Anti-Sune', 'R U R'' U R U2 R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 26),
  'R U2 R'' U'' R U'' R''',
  true,
  true
)
ON CONFLICT DO NOTHING;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 26),
  'R U'' R'' U'' R U'' R''',
  false,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 27
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 27, 'OLL 27', 'Cross, Sune', 'R U2 R'' U'' R U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 27),
  'R U R'' U R U2 R''',
  true,
  true
)
ON CONFLICT DO NOTHING;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 27),
  'R U R'' U R U'' R''',
  false,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 28
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 28, 'OLL 28', 'Arrow', 'M U'' M'' U2 M U'' M''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 28),
  'M U M'' U2 M U M''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 29
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 29, 'OLL 29', 'Awkward', 'R U'' R'' F'' U F R U R'' U R U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 29),
  'R U R'' U'' R U'' R'' F'' U'' F R U R''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 30
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 30, 'OLL 30', 'Awkward', 'F U R U2 R'' U R U2 R'' U'' F''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 30),
  'F U R U2 R'' U'' R U2 R'' U'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 31
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 31, 'OLL 31', 'P shape', 'R'' F R U R'' U'' F'' U R')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 31),
  'R'' U'' F U R U'' R'' F'' R',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 32
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 32, 'OLL 32', 'P shape', 'f R'' F'' R U R U'' R'' S''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 32),
  'S R U R'' U'' R'' F R f''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 33
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 33, 'OLL 33', 'T shape', 'F R'' F'' R U R U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 33),
  'R U R'' U'' R'' F R F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 34
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 34, 'OLL 34', 'C shape', 'F U R'' U'' R'' F'' R U R2 U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 34),
  'R U R2 U'' R'' F R U R U'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 35
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 35, 'OLL 35', 'Fish', 'R U2 R'' F R'' F'' R2 U2 R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 35),
  'R U2 R2 F R F'' R U2 R''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 36
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 36, 'OLL 36', 'W shape', 'F'' L F L'' U'' L'' U'' L U L'' U L')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 36),
  'L'' U'' L U'' L'' U L U L F'' L'' F',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 37
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 37, 'OLL 37', 'Fish', 'F R U'' R'' U'' R U R'' F''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 37),
  'F R U'' R'' U'' R U R'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 38
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 38, 'OLL 38', 'W shape', 'F R'' F'' R U R U R'' U'' R U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 38),
  'R U R'' U R U'' R'' U'' R'' F R F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 39
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 39, 'OLL 39', 'Big Lightning', 'L U F'' U'' L'' U L F L''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 39),
  'L F'' L'' U'' L U F U'' L''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 40
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 40, 'OLL 40', 'Big Lightning', 'R'' U'' F U R U'' R'' F'' R')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 40),
  'R'' F R U R'' U'' F'' U R',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 41
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 41, 'OLL 41', 'Awkward', 'F U R U'' R'' F'' R U2 R'' U'' R U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 41),
  'R U R'' U R U2 R'' F R U R'' U'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 42
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 42, 'OLL 42', 'Awkward', 'F U R U'' R'' F'' R'' U2 R U R'' U R')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 42),
  'R'' U'' R U'' R'' U2 R F R U R'' U'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 43
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 43, 'OLL 43', 'P shape', 'f'' U'' L'' U L f')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 43),
  'f'' L'' U'' L U f',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 44
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 44, 'OLL 44', 'P shape', 'f U R U'' R'' f''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 44),
  'f R U R'' U'' f''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 45
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 45, 'OLL 45', 'T shape', 'F U R U'' R'' F''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 45),
  'F R U R'' U'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 46
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 46, 'OLL 46', 'C shape', 'R'' U'' F R'' F'' R U R')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 46),
  'R'' U'' R'' F R F'' U R',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 47
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 47, 'OLL 47', 'Small L', 'R'' U'' F R'' F'' R F R'' F'' R U R')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 47),
  'R'' U'' R'' F R F'' R'' F R F'' U R',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 48
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 48, 'OLL 48', 'Small L', 'F U R U'' R'' U R U'' R'' F''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 48),
  'F R U R'' U'' R U R'' U'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 49
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 49, 'OLL 49', 'Small L', 'r'' U r2 U'' r2 U'' r2 U r')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 49),
  'r U'' r2 U r2 U r2 U'' r',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 50
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 50, 'OLL 50', 'Small L', 'r U'' r2 U r2 U r2 U'' r''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 50),
  'r'' U r2 U'' r2 U'' r2 U r''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 51
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 51, 'OLL 51', 'Line', 'f U R U'' R'' U R U'' R'' f''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 51),
  'f R U R'' U'' R U R'' U'' f''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 52
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 52, 'OLL 52', 'Line', 'F R U R'' y'' U R'' U'' R U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 52),
  'R U R'' U R U'' y R U'' R'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 53
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 53, 'OLL 53', 'Small L', 'r'' U'' R U'' R'' U R U'' R'' U2 r')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 53),
  'r'' U2 R U R'' U'' R U R'' U r',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 54
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 54, 'OLL 54', 'Small L', 'r U R'' U R U'' R'' U R U2 r''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 54),
  'r U2 R'' U'' R U R'' U'' R U'' r''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 55
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 55, 'OLL 55', 'Line', 'R U'' R'' U'' R U R2 F R2 U R'' U'' R'' F'' R')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 55),
  'R'' F R U R U'' R2 F'' R2 U'' R'' U R U R''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 56
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 56, 'OLL 56', 'Line', 'r U r'' R U R'' U'' R U R'' U'' r U'' r''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 56),
  'r U r'' U R U'' R'' U R U'' R'' r U'' r''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- OLL 57
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'oll', 57, 'OLL 57', 'Line', 'r U R'' U'' M U R U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'oll' AND case_number = 57),
  'R U R'' U'' M'' U R U'' r''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- =============================================================
-- 333 PLL (21 cases)
-- =============================================================

-- Aa Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 1, 'Aa Perm', 'Adjacent corner swap. Headlights at back, block on the left.', 'x L'' U'' L D2 L'' U L D2 L2 x''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 1),
  'x L2 D2 L'' U'' L D2 L'' U L'' x''',
  true,
  true
)
ON CONFLICT DO NOTHING;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved, label)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 1),
  'y'' x'' R'' D R'' U2 R D'' R'' U2 R2 x',
  false,
  true, 'R moves variant'
)
ON CONFLICT DO NOTHING;

-- Ab Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 2, 'Ab Perm', 'Adjacent corner swap. Headlights at back, block on the right.', 'x L'' U L'' D2 L U'' L'' D2 L2 x''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 2),
  'x L2 D2 L U L'' D2 L U'' L x''',
  true,
  true
)
ON CONFLICT DO NOTHING;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved, label)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 2),
  'y x'' R2 D2 R'' U'' R D2 R'' U R'' x',
  false,
  true, 'R moves variant'
)
ON CONFLICT DO NOTHING;

-- E Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 3, 'E Perm', 'Diagonal corner swap. Edges solved, no blocks.', 'x'' D'' L'' U'' L D L'' U L D'' L'' U L D L'' U'' L x')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 3),
  'x'' L'' U L D'' L'' U'' L D L'' U'' L D'' L'' U L D x',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- F Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 4, 'F Perm', 'Adjacent corner swap, adjacent edge swap. Full block on one side.', 'R'' U'' R U'' R'' U R U R2 F'' R U R U'' R'' F U R')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 4),
  'R'' U'' F'' R U R'' U'' R'' F R2 U'' R'' U'' R U R'' U R',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- Ga Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 5, 'Ga Perm', 'Adjacent corner swap, edge cycle. Headlights on left, block front-right.', 'D R'' U'' R D'' U R2 U R'' U R U'' R U'' R2')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 5),
  'R2 U R'' U R'' U'' R U'' R2 U'' D R'' U R D''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- Gb Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 6, 'Gb Perm', 'Adjacent corner swap, edge cycle. Headlights on left, block back-right.', 'R2 u R'' U R'' U'' R u'' R2 F'' U F')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 6),
  'F'' U'' F R2 u R'' U R U'' R u'' R2',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- Gc Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 7, 'Gc Perm', 'Adjacent corner swap, edge cycle. Headlights on left, block back-left.', 'D'' R U R'' D U'' R2 U'' R U'' R'' U R'' U R2')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 7),
  'R2 U'' R U'' R U R'' U R2 U D'' R U'' R'' D',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- Gd Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 8, 'Gd Perm', 'Adjacent corner swap, edge cycle. Headlights on left, block front-left.', 'R2 u'' R U R'' U R u R2 y R U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 8),
  'R U R'' y'' R2 u'' R U'' R'' U R'' u R2',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- H Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 9, 'H Perm', 'Opposite edge swap. Corners solved.', 'M2 U'' M2 U2 M2 U'' M2')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 9),
  'M2 U M2 U2 M2 U M2',
  true,
  true
)
ON CONFLICT DO NOTHING;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 9),
  'M2 U'' M2 U2 M2 U'' M2',
  false,
  true
)
ON CONFLICT DO NOTHING;

-- Ja Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 10, 'Ja Perm', 'Adjacent corner swap, adjacent edge swap. Block forms a ''J'' shape on left.', 'x U2 r'' U'' r U2 R'' F R'' F'' R2 x''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 10),
  'x R2 F R F'' R U2 r'' U r U2 x''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- Jb Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 11, 'Jb Perm', 'Adjacent corner swap, adjacent edge swap. Block forms a ''J'' shape on right.', 'U R U R2 F'' R U R U'' R'' F R U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 11),
  'R U R'' F'' R U R'' U'' R'' F R2 U'' R'' U''',
  true,
  true
)
ON CONFLICT DO NOTHING;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved, label)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 11),
  'R U2 R'' U'' R U2 L'' U R'' U'' L',
  false,
  true, 'Alternate'
)
ON CONFLICT DO NOTHING;

-- Na Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 12, 'Na Perm', 'Diagonal corner swap, parallel edge swap. Two 1x1x3 blocks.', 'R U R'' U2 R U R2 F'' R U R U'' R'' F R U'' R'' U'' R U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 12),
  'R U R'' U R U R'' F'' R U R'' U'' R'' F R2 U'' R'' U2 R U'' R''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- Nb Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 13, 'Nb Perm', 'Diagonal corner swap, parallel edge swap. Two 1x1x3 blocks.', 'F r'' F'' r U r U'' r2 D'' F r U r'' F'' D r')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 13),
  'r'' D'' F r U'' r'' F'' D r2 U r'' U'' r'' F r F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- Ra Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 14, 'Ra Perm', 'Adjacent corner swap, adjacent edge swap. Headlights at right, block in back.', 'R U2 R'' U'' R'' F'' R U2 R U2 R'' F R U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 14),
  'R U R'' F'' R U2 R'' U2 R'' F R U R U2 R''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- Rb Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 15, 'Rb Perm', 'Adjacent corner swap, adjacent edge swap. Headlights at back, block on right.', 'U R2 F R U R U'' R'' F'' R U2 R'' U2 R')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 15),
  'R'' U2 R U2 R'' F R U R'' U'' R'' F'' R2 U''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- T Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 16, 'T Perm', 'Adjacent corner swap, opposite edge swap. Headlights on left.', 'F R U'' R'' U R U R2 F'' R U R U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 16),
  'R U R'' U'' R'' F R2 U'' R'' U'' R U R'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 16),
  'R U R'' U'' R'' F R2 U'' R'' U'' R U R'' F''',
  false,
  true
)
ON CONFLICT DO NOTHING;

-- Ua Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 17, 'Ua Perm', '3-cycle of edges, moving counter-clockwise. Corners solved.', 'M2 U'' M U2 M'' U'' M2')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 17),
  'M2 U M U2 M'' U M2',
  true,
  true
)
ON CONFLICT DO NOTHING;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved, label)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 17),
  'R U'' R U R U R U'' R'' U'' R2',
  false,
  true, 'R U variant'
)
ON CONFLICT DO NOTHING;

-- Ub Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 18, 'Ub Perm', '3-cycle of edges, moving clockwise. Corners solved.', 'M2 U M U2 M'' U M2')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 18),
  'M2 U'' M U2 M'' U'' M2',
  true,
  true
)
ON CONFLICT DO NOTHING;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved, label)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 18),
  'R2 U R U R'' U'' R'' U'' R'' U R''',
  false,
  true, 'R U variant'
)
ON CONFLICT DO NOTHING;

-- V Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 19, 'V Perm', 'Diagonal corner swap, adjacent edge swap. 2x2x1 block.', 'F'' R'' F'' R U'' R U R2 F R d R U'' R')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 19),
  'R'' U R'' d'' R'' F'' R2 U'' R'' U R'' F R F',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- Y Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 20, 'Y Perm', 'Diagonal corner swap, opposite edge swap. Two 1x1x2 blocks.', 'F R'' F'' R U R U'' R'' F R U'' R'' U R U R'' F''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 20),
  'F R U'' R'' U'' R U R'' F'' R U R'' U'' R'' F R F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- Z Perm
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('333', 'pll', 21, 'Z Perm', 'Adjacent 2-swaps of edges. Corners solved.', 'M U2 M2 U2 M U'' M2 U'' M2')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 21),
  'M2 U M2 U M'' U2 M2 U2 M''',
  true,
  true
)
ON CONFLICT DO NOTHING;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved, label)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '333' AND subset = 'pll' AND case_number = 21),
  'M'' U M2 U M2 U M'' U2 M2',
  false,
  true, 'Alternate'
)
ON CONFLICT DO NOTHING;

-- =============================================================
-- 222 ORTEGA (10 cases)
-- =============================================================

-- Sune
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('222', 'ortega', 1, 'Sune', 'One corner oriented correctly on the opposite face.', 'R U R'' U R U2 R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '222' AND subset = 'ortega' AND case_number = 1),
  'R U R'' U R U2 R''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- Anti-Sune
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('222', 'ortega', 2, 'Anti-Sune', 'One corner oriented correctly (mirror of Sune).', 'R U2 R'' U'' R U'' R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '222' AND subset = 'ortega' AND case_number = 2),
  'R U2 R'' U'' R U'' R''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- Pi / Bruno
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('222', 'ortega', 3, 'Pi / Bruno', 'Two diagonal corners oriented.', 'F R U R'' U'' R U R'' U'' F''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '222' AND subset = 'ortega' AND case_number = 3),
  'F R U R'' U'' R U R'' U'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- H / Blinker
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('222', 'ortega', 4, 'H / Blinker', 'Two adjacent corners oriented on opposite sides.', 'F R U R'' U'' F2 L'' U'' L U F')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '222' AND subset = 'ortega' AND case_number = 4),
  'R2 U2 R U2 R2',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- L / Headlights
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('222', 'ortega', 5, 'L / Headlights', 'Two adjacent corners oriented on the same side.', 'F R U'' R'' U'' R U R'' F''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '222' AND subset = 'ortega' AND case_number = 5),
  'F R U'' R'' U'' R U R'' F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- U / Bowtie
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('222', 'ortega', 6, 'U / Bowtie', 'No corners oriented on the opposite face (all twisted).', 'R U2 R2 U'' R2 U'' R2 U2 R')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '222' AND subset = 'ortega' AND case_number = 6),
  'R U2 R2 U'' R2 U'' R2 U2 R',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- T / Chameleon
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('222', 'ortega', 7, 'T / Chameleon', 'Two diagonal corners oriented, opposite diagonal.', 'R U R'' U'' R'' F R F''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '222' AND subset = 'ortega' AND case_number = 7),
  'R U R'' U'' R'' F R F''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- Adjacent / Adjacent
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('222', 'ortega', 8, 'Adjacent / Adjacent', 'Adjacent swap on both layers.', 'R U'' R F2 R'' U R''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '222' AND subset = 'ortega' AND case_number = 8),
  'R U'' R F2 R'' U R''',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- Diagonal / Diagonal
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('222', 'ortega', 9, 'Diagonal / Diagonal', 'Diagonal swap on both layers.', 'R2 F2 R2')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '222' AND subset = 'ortega' AND case_number = 9),
  'R2 F2 R2',
  true,
  true
)
ON CONFLICT DO NOTHING;

-- Adjacent / Diagonal
INSERT INTO public.algorithm_cases (puzzle_type, subset, case_number, name, description, cube_state)
VALUES ('222', 'ortega', 10, 'Adjacent / Diagonal', 'Adjacent swap on top, diagonal swap on bottom.', 'R U R'' U'' R'' F R2 U'' R'' U'' R U R'' F''')
ON CONFLICT (puzzle_type, subset, case_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  cube_state = EXCLUDED.cube_state;

INSERT INTO public.algorithms (case_id, moves, is_main, is_approved, label)
VALUES (
  (SELECT id FROM public.algorithm_cases WHERE puzzle_type = '222' AND subset = 'ortega' AND case_number = 10),
  'R U R'' U'' R'' F R2 U'' R'' U'' R U R'' F''',
  true,
  true, 'T Perm'
)
ON CONFLICT DO NOTHING;

COMMIT;
